[GLOBAL]
pants_version = "2.14.0"

backend_packages = [
    "pants.backend.python",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
    '/',
]

[python]

interpreter_constraints = ["CPython==3.10.*"]
# This will become the default in Pants 2.15.
tailor_pex_binary_targets = false
